### ISSUE TITLE
[UX] Add a debug button

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/debugger#180]
I was just playing around with the binder and found it a little strange that you debugged something by clicking the RUN button (when the debugger was active?)

It would be good if there were an explicit debug button to start a debug session - e.g.
![image](https://user-images.githubusercontent.com/881019/68817933-ff088700-06ce-11ea-8c57-097c5b10fc09.png)

**Comment by dhirschfeld** [comment]
In a similar vein it would be handy if next to the continue/step* buttons there were also STOP and RESTART buttons

**Comment by dhirschfeld** [comment]
Possibly related to #176?

**Comment by jtpio** [comment]
Thanks @dhirschfeld for the feedback!

This is something that has been discussed several times, but for now we decided to automatically start the debugger whenever possible.

One of the reasons for that is that introducing one more button to start debugging might add some friction, and ideally we should be able to hit the breakpoints in a cell by just executing it using the normal flow (Ctrl-Enter or the run button).

Another source of inspiration are the developer tools in browsers like Firefox and Chrome. The debugger is always "there", meaning that we can add breakpoints and start debugging without manually starting the debugger.

The related issues and PRs: https://github.com/jupyterlab/debugger/pull/126, https://github.com/jupyterlab/debugger/issues/117 and https://github.com/jupyterlab/debugger/issues/110.

**Comment by jtpio** [comment]
Maybe there could also be an option in the Advanced Settings editor, to automatically start the debugger or not. If disabled then the buttons would be shown.

**Comment by dhirschfeld** [comment]
I was trying to debug a notebook cell - but obviously there's nothing to debug until it starts executing for which you have to press the run icon.

I think it would be clearer if the run button ran the cell without triggering the debugger whilst a debug button would stop at the breakpoints.

**Comment by dhirschfeld** [comment]
In anycase it's ***amazing*** to have this functionality in JupyterLab so congratulations & I'm excited to see where it goes! 🚀

**Comment by KsavinN** [comment]
@dhirschfeld Thank you for your advice.

**Comment by jtpio** [comment]
> I was trying to debug a notebook cell - but obviously there's nothing to debug until it starts executing for which you have to press the run icon.

Debugging will have the same effect as running the code directly. It will mutate the state of the kernel since it's executing code in the same interactive session.

> I think it would be clearer if the run button ran the cell without triggering the debugger whilst a debug button would stop at the breakpoints.

That would be the case with breakpoints that have been deactivate / disabled.

**Comment by jtpio** [comment]
@dhirschfeld a new button was recently added to the toolbar to enable and disable debugging for a particular notebook, console or file. And it looks like this:

![](https://user-images.githubusercontent.com/591645/70950871-1df99080-2062-11ea-937b-12e9db9633fa.gif)

In case you want to try it on Binder (from the `master` branch):

[![Binder-master](https://img.shields.io/badge/master-binder-F5A252.svg?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFkAAABZCAMAAABi1XidAAAB8lBMVEX///9XmsrmZYH1olJXmsr1olJXmsrmZYH1olJXmsr1olJXmsrmZYH1olL1olJXmsr1olJXmsrmZYH1olL1olJXmsrmZYH1olJXmsr1olL1olJXmsrmZYH1olL1olJXmsrmZYH1olL1olL0nFf1olJXmsrmZYH1olJXmsq8dZb1olJXmsrmZYH1olJXmspXmspXmsr1olL1olJXmsrmZYH1olJXmsr1olL1olJXmsrmZYH1olL1olLeaIVXmsrmZYH1olL1olL1olJXmsrmZYH1olLna31Xmsr1olJXmsr1olJXmsrmZYH1olLqoVr1olJXmsr1olJXmsrmZYH1olL1olKkfaPobXvviGabgadXmsqThKuofKHmZ4Dobnr1olJXmsr1olJXmspXmsr1olJXmsrfZ4TuhWn1olL1olJXmsqBi7X1olJXmspZmslbmMhbmsdemsVfl8ZgmsNim8Jpk8F0m7R4m7F5nLB6jbh7jbiDirOEibOGnKaMhq+PnaCVg6qWg6qegKaff6WhnpKofKGtnomxeZy3noG6dZi+n3vCcpPDcpPGn3bLb4/Mb47UbIrVa4rYoGjdaIbeaIXhoWHmZYHobXvpcHjqdHXreHLroVrsfG/uhGnuh2bwj2Hxk17yl1vzmljzm1j0nlX1olL3AJXWAAAAbXRSTlMAEBAQHx8gICAuLjAwMDw9PUBAQEpQUFBXV1hgYGBkcHBwcXl8gICAgoiIkJCQlJicnJ2goKCmqK+wsLC4usDAwMjP0NDQ1NbW3Nzg4ODi5+3v8PDw8/T09PX29vb39/f5+fr7+/z8/Pz9/v7+zczCxgAABC5JREFUeAHN1ul3k0UUBvCb1CTVpmpaitAGSLSpSuKCLWpbTKNJFGlcSMAFF63iUmRccNG6gLbuxkXU66JAUef/9LSpmXnyLr3T5AO/rzl5zj137p136BISy44fKJXuGN/d19PUfYeO67Znqtf2KH33Id1psXoFdW30sPZ1sMvs2D060AHqws4FHeJojLZqnw53cmfvg+XR8mC0OEjuxrXEkX5ydeVJLVIlV0e10PXk5k7dYeHu7Cj1j+49uKg7uLU61tGLw1lq27ugQYlclHC4bgv7VQ+TAyj5Zc/UjsPvs1sd5cWryWObtvWT2EPa4rtnWW3JkpjggEpbOsPr7F7EyNewtpBIslA7p43HCsnwooXTEc3UmPmCNn5lrqTJxy6nRmcavGZVt/3Da2pD5NHvsOHJCrdc1G2r3DITpU7yic7w/7Rxnjc0kt5GC4djiv2Sz3Fb2iEZg41/ddsFDoyuYrIkmFehz0HR2thPgQqMyQYb2OtB0WxsZ3BeG3+wpRb1vzl2UYBog8FfGhttFKjtAclnZYrRo9ryG9uG/FZQU4AEg8ZE9LjGMzTmqKXPLnlWVnIlQQTvxJf8ip7VgjZjyVPrjw1te5otM7RmP7xm+sK2Gv9I8Gi++BRbEkR9EBw8zRUcKxwp73xkaLiqQb+kGduJTNHG72zcW9LoJgqQxpP3/Tj//c3yB0tqzaml05/+orHLksVO+95kX7/7qgJvnjlrfr2Ggsyx0eoy9uPzN5SPd86aXggOsEKW2Prz7du3VID3/tzs/sSRs2w7ovVHKtjrX2pd7ZMlTxAYfBAL9jiDwfLkq55Tm7ifhMlTGPyCAs7RFRhn47JnlcB9RM5T97ASuZXIcVNuUDIndpDbdsfrqsOppeXl5Y+XVKdjFCTh+zGaVuj0d9zy05PPK3QzBamxdwtTCrzyg/2Rvf2EstUjordGwa/kx9mSJLr8mLLtCW8HHGJc2R5hS219IiF6PnTusOqcMl57gm0Z8kanKMAQg0qSyuZfn7zItsbGyO9QlnxY0eCuD1XL2ys/MsrQhltE7Ug0uFOzufJFE2PxBo/YAx8XPPdDwWN0MrDRYIZF0mSMKCNHgaIVFoBbNoLJ7tEQDKxGF0kcLQimojCZopv0OkNOyWCCg9XMVAi7ARJzQdM2QUh0gmBozjc3Skg6dSBRqDGYSUOu66Zg+I2fNZs/M3/f/Grl/XnyF1Gw3VKCez0PN5IUfFLqvgUN4C0qNqYs5YhPL+aVZYDE4IpUk57oSFnJm4FyCqqOE0jhY2SMyLFoo56zyo6becOS5UVDdj7Vih0zp+tcMhwRpBeLyqtIjlJKAIZSbI8SGSF3k0pA3mR5tHuwPFoa7N7reoq2bqCsAk1HqCu5uvI1n6JuRXI+S1Mco54YmYTwcn6Aeic+kssXi8XpXC4V3t7/ADuTNKaQJdScAAAAAElFTkSuQmCC)](https://mybinder.org/v2/gh/jupyterlab/debugger/master?urlpath=/lab/tree/examples/index.ipynb)

Otherwise a new `rc` release is coming soon.

**Comment by dhirschfeld** [comment]
I quite like the new VSCode icon as it combines the concept of running & debugging at the same time:

![](https://code.visualstudio.com/assets/updates/1_42/debug-activity.png)

**Comment by jtpio** [comment]
Right, in VS code this tab is also used to define arbitrary launch configurations, which is probably why having the debug icon only was "not enough".
