### ISSUE TITLE
New Line Issue with breakpoints

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/debugger#188]
Discussion was move to #171.

![enterIssue](https://user-images.githubusercontent.com/34033913/68871345-8f10f580-06fc-11ea-939f-a3d45a59cfae.gif)

**Comment by jtpio** [comment]
This is the result of https://github.com/jupyterlab/debugger/pull/164, and it's also related to https://github.com/jupyterlab/debugger/issues/171.

It comes down to the problem of being able to send the content of cell with the breakpoints to the kernel before executing it (with the `dumpCell` request). So we are able to break on `execute_request`.

Under the hood the kernel creates new temporary files and keeps track of them, which is why they keep showing up in the UI.

**Comment by KsavinN** [comment]
I guess #171  and that will be discussed tomorrow

**Comment by jtpio** [comment]
Should we move the discussion to #171?

**Comment by KsavinN** [comment]
Yeah i think we should.
