### ISSUE TITLE
support for asynchronous calls using await outside async functions

### ISSUE THREAD

**Issue by iamorlando** [jupyterlab/debugger#413]
Hi, after some testing I can say running any async calls hangs the debugged. e.g.
```(python)
from asyncio import sleep
await sleep(1)
```

is there any work around or support for this?

**Comment by SylvainCorlay** [comment]
Currently, the xeus-python kernel does not support direct calls to await. It is not really valid since there isn't really an event loop running.

([auto-await](https://ipython.readthedocs.io/en/stable/interactive/autoawait.html#asynchronous-in-repl-autoawait) is a rather recent addition in IPython from late 2018.

**Comment by SylvainCorlay** [comment]
Closing and referencing https://github.com/jupyter-xeus/xeus-python/issues/175 for tracking auto-await support in xeus-python.
