### ISSUE TITLE
Register xeus kernel to environment

### ISSUE THREAD

**Issue by enryH** [jupyterlab/debugger#476]
Is there a way to register the xeus-kernel to a project's virtual environment similar to [ipython](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments)? 

Normally I have jupyter lab/ notebook only installed in a base environment and link several ipykernels to it. Would be great if this is also possible with xeus-python.

Best, Henry

**Comment by jtpio** [comment]
@enryH by "link" you mean being able to use kernels from other environments?

If possible it's usually simpler to install the kernels in the same environments as the other Jupyter packages. Otherwise it should be possible by writing the kernel spec file (`kernel.json`) at the right location.

Also this sounds more related to `xeus-python` itself than the debugger extension. Would it be possible to move the issue to the `xeus-python` repo? https://github.com/jupyter-xeus/xeus-python

Thanks!

**Comment by enryH** [comment]
Thanks for the clarification! There is already some [discussion](vhttps://github.com/jupyter-xeus/xeus-python/issues/271) in issues around that topic in the xeus-python repo. 

Cheers, Henry
