### ISSUE TITLE
Debugger is disabled after restarting notebook

### ISSUE THREAD

**Issue by rickygao** [jupyterlab/debugger#478]
Debugger is disabled and all breakpoints are lost, after clicking the "Restart the kernel, then re-run the whole notebook" or "Restart the kernel" in the toolbar. Is it an expected behavior? I would like after clicking "restart and re-run" button, debugger is immediately enabled and all breakpoints are reserved, which makes debugging easier, just like in some IDEs.

Package versions are as follows:
- jupyter=^2.1.4
- xeus-python=^0.8.0
- @jupyter/debugger=^0.3.0-beta.1

**Comment by jtpio** [comment]
Thanks @rickygao.

>  "Restart the kernel, then re-run the whole notebook" or "Restart the kernel" in the toolbar. Is it an expected behavior?

Yes this is expected behavior at the moment. Some IDEs implement persistent breakpoints and some don't.

For now the JupyterLab debugger doesn't restore the breakpoints on kernel restart but it sounds like it should be technically possible. The kernel could for example keep the state of the breakpoints.

**Comment by jtpio** [comment]
Closing as answered.

@rickygao feel free to open a new issue in https://github.com/jupyterlab/jupyterlab (which now includes the debugger extension) if you think this should still be considered!
