### ISSUE TITLE
Magic command not working with xeus-python

### ISSUE THREAD

**Issue by pratikchhapolika** [jupyterlab/debugger#492]
I am trying to run magic commmands in jupyter lab which I recently installed with some debugger extension from this link:

https://github.com/jupyterlab/debugger

When I run this command:

```
import numpy as np
from numpy.random import randint

 #A function to simulate one million dice throws.

def one_million_dice():
   return randint(low=1, high=7, size=1000000)
```

```
%%time
throws = one_million_dice()
mean = np.mean(throws)
```

```
Error:

 ---------------------------------------------------------------------------
SyntaxError                               Traceback (most recent call last)
File C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\ast.py, in parse:
Line 35:    return compile(source, filename, mode, PyCF_ONLY_AST)

SyntaxError: invalid syntax (<string>, line 1)
---------------------------------------------------------------------------
```

**Question 1:** How to see the complete traceback in Jupyter lab?
**Question2:** How to fix it?

**Comment by jtpio** [comment]
Thanks @pratikchhapolika.

This looks more related to `xeus-python` than the debugger extension.

We can close this issue and open a new one on the repo: https://github.com/jupyter-xeus/xeus-python

The latest `xeus-python` (0.8.1) should have support for some of the magics, but not all. You might have to use `%%timeit` instead of `%%time`.

**Comment by pratikchhapolika** [comment]
Moving this issue to xeus-python  https://github.com/jupyter-xeus/xeus-python.
