### ISSUE TITLE
JupyterLab debugger overrides colors of custom theme

### ISSUE THREAD

**Issue by zombba** [jupyterlab/debugger#517]
Hello. 
Is it possible use css variables, defined in the custom theme ?
Now jupyter-debugger overrides colors of 'Solarized dark' theme.
![image](https://user-images.githubusercontent.com/52904454/88473573-1e87cd00-cf49-11ea-9003-7bcc893c5111.png)

Of course, i created issue for creator of 'Solarized dark' theme.
It is <a href=https://github.com/AllanChain/jupyterlab-theme-solarized-dark/issues/3>here</a>

**Comment by jtpio** [comment]
Thanks @zombba.

The table view for the variables uses the `@lumino/datagrid` and defines the styles a bit differently than the usual CSS variables.

For example in the debugger extension it is defined here:

https://github.com/jupyterlab/debugger/blob/4020282dbfa1fbf57a2b7c2b1e1360b5b8d18cbc/src/panels/variables/grid.ts#L312-L353

And for the CSV extension in JupyterLab (which also uses the data grid):

https://github.com/jupyterlab/jupyterlab/blob/0b88d64b622fc03f4c06ce9cceaa13bc443db468/packages/csvviewer-extension/src/index.ts#L257-L302

For the CSV view it maybe doesn't stick out too much since it's in its own panel:

![image](https://user-images.githubusercontent.com/591645/88517321-f5217c80-cfee-11ea-8be4-cf4d9a941ea5.png)

**Comment by jtpio** [comment]
Ideally these two extensions would be able to get the computed CSS styles directly, so they can be passed to the data grid.

**Comment by afshin** [comment]
Fixed in https://github.com/jupyterlab/debugger/pull/523
